# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # configure resolvers
    resolvers :
        default :
            web_path : ~

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    # your filter sets are defined here
    filter_sets :
        cache : ~

        user_page_picture:
            quality: 100
            filters:
                thumbnail: { size : [240, 240], mode : outbound }

        project_user_picture:
            quality: 40
            filters:
                thumbnail: { size: [48, 48], mode: outbound }

        navbar_user:
            quality: 100
            default_image: /assets/uploads/users/picture/default_user
            filters:
                thumbnail: { size: [48, 48], mode: outbound }