vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /assets/uploads/users/picture
            upload_destination: '%kernel.project_dir%/public/assets/uploads/users/picture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        task_document:
            uri_prefix: /assets/uploads/tasks/documents
            upload_destination: '%kernel.project_dir%/public/assets/uploads/tasks/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
